# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gpa_qt.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(973, 550)
        MainWindow.setMinimumSize(QtCore.QSize(750, 400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/graduate.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("#scrollArea {\n"
"border: 1px solid rgb(222,222,222);\n"
"border-radius: 10px;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.layout_central = QtWidgets.QVBoxLayout(self.centralwidget)
        self.layout_central.setSpacing(9)
        self.layout_central.setObjectName("layout_central")
        self.frame_top = QtWidgets.QFrame(self.centralwidget)
        self.frame_top.setStyleSheet("QLabel {\n"
"font: 87 10pt \"Segoe UI Black\";\n"
"}\n"
"\n"
"QSpinBox, QDoubleSpinBox{\n"
"border: 1px solid rgb(200,200,200);\n"
"background-color: rgb(244,244,244);\n"
"border-radius: 8px;\n"
"font: 87 10pt \"Segoe UI Black\";\n"
"}\n"
"\n"
"#frame_top{\n"
"border: 1px solid rgb(222,222,222);\n"
"border-radius: 10px;\n"
"background-color: rgb(232,229,233);\n"
"}\n"
"#frame_top > *{\n"
"padding-left: 10px;\n"
"\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(232,229,233);\n"
"font: 87 10pt \"Segoe UI Black\";\n"
"border-radius: 10px;\n"
"border: 1px solid rgb(222,222,222)\n"
"}")
        self.frame_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.layout_top = QtWidgets.QGridLayout(self.frame_top)
        self.layout_top.setHorizontalSpacing(25)
        self.layout_top.setVerticalSpacing(0)
        self.layout_top.setObjectName("layout_top")
        self.spinbox_input_agno = QtWidgets.QDoubleSpinBox(self.frame_top)
        self.spinbox_input_agno.setMinimumSize(QtCore.QSize(100, 35))
        self.spinbox_input_agno.setMaximumSize(QtCore.QSize(100, 16777215))
        self.spinbox_input_agno.setMaximum(4.0)
        self.spinbox_input_agno.setSingleStep(0.1)
        self.spinbox_input_agno.setObjectName("spinbox_input_agno")
        self.layout_top.addWidget(self.spinbox_input_agno, 2, 1, 1, 1)
        self.spinbox_input_kredi = QtWidgets.QSpinBox(self.frame_top)
        self.spinbox_input_kredi.setMinimumSize(QtCore.QSize(100, 35))
        self.spinbox_input_kredi.setMaximumSize(QtCore.QSize(100, 35))
        self.spinbox_input_kredi.setMinimum(0)
        self.spinbox_input_kredi.setMaximum(250)
        self.spinbox_input_kredi.setSingleStep(10)
        self.spinbox_input_kredi.setProperty("value", 0)
        self.spinbox_input_kredi.setObjectName("spinbox_input_kredi")
        self.layout_top.addWidget(self.spinbox_input_kredi, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_top.addItem(spacerItem, 2, 2, 1, 1)
        self.text_tamamlanmis_kredi = QtWidgets.QLabel(self.frame_top)
        self.text_tamamlanmis_kredi.setMinimumSize(QtCore.QSize(200, 35))
        self.text_tamamlanmis_kredi.setObjectName("text_tamamlanmis_kredi")
        self.layout_top.addWidget(self.text_tamamlanmis_kredi, 1, 0, 1, 1)
        self.gpa_input_text = QtWidgets.QLabel(self.frame_top)
        self.gpa_input_text.setMinimumSize(QtCore.QSize(0, 35))
        self.gpa_input_text.setObjectName("gpa_input_text")
        self.layout_top.addWidget(self.gpa_input_text, 2, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.frame_top)
        self.frame.setMinimumSize(QtCore.QSize(150, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_kaydet = QtWidgets.QPushButton(self.frame)
        self.button_kaydet.setMinimumSize(QtCore.QSize(100, 35))
        self.button_kaydet.setMaximumSize(QtCore.QSize(100, 35))
        self.button_kaydet.setStyleSheet("QPushButton{\n"
"border: 1px solid rgb(211,211,211);\n"
"border-radius: 10px;\n"
"background-color: gray;\n"
"color: rgb(211,211,211);\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"background-color: rgb(111,111,111);\n"
"color: white;\n"
"}")
        self.button_kaydet.setObjectName("button_kaydet")
        self.horizontalLayout.addWidget(self.button_kaydet)
        self.layout_top.addWidget(self.frame, 2, 3, 1, 1)
        self.layout_central.addWidget(self.frame_top)
        self.frame_middle = QtWidgets.QFrame(self.centralwidget)
        self.frame_middle.setStyleSheet("")
        self.frame_middle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_middle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_middle.setObjectName("frame_middle")
        self.layout_mid = QtWidgets.QVBoxLayout(self.frame_middle)
        self.layout_mid.setSpacing(0)
        self.layout_mid.setObjectName("layout_mid")
        self.frame_ders_ekle = QtWidgets.QFrame(self.frame_middle)
        self.frame_ders_ekle.setStyleSheet("font: 87 10pt \"Segoe UI Black\";\n"
"")
        self.frame_ders_ekle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_ders_ekle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_ders_ekle.setObjectName("frame_ders_ekle")
        self.layout_ders_ekle = QtWidgets.QHBoxLayout(self.frame_ders_ekle)
        self.layout_ders_ekle.setObjectName("layout_ders_ekle")
        self.button_ders_ekle = QtWidgets.QPushButton(self.frame_ders_ekle)
        self.button_ders_ekle.setMinimumSize(QtCore.QSize(110, 35))
        self.button_ders_ekle.setMaximumSize(QtCore.QSize(110, 16777215))
        self.button_ders_ekle.setStyleSheet("QPushButton{\n"
"border: 1px solid rgb(111,111,111);\n"
"border-radius: 10px;\n"
"background-color: white;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"background-color: rgb(111,111,111);\n"
"color: white;\n"
"}")
        self.button_ders_ekle.setObjectName("button_ders_ekle")
        self.layout_ders_ekle.addWidget(self.button_ders_ekle)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_ders_ekle.addItem(spacerItem1)
        self.button_tumunu_sil = QtWidgets.QPushButton(self.frame_ders_ekle)
        self.button_tumunu_sil.setMinimumSize(QtCore.QSize(120, 35))
        self.button_tumunu_sil.setMaximumSize(QtCore.QSize(120, 35))
        self.button_tumunu_sil.setStyleSheet("QPushButton {\n"
"border: 1px solid rgb(211,111,111);\n"
"background-color: white;\n"
"color:rgb(211,111,111);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"background-color:rgb(211,111,111);\n"
"color:white;\n"
"}")
        self.button_tumunu_sil.setObjectName("button_tumunu_sil")
        self.layout_ders_ekle.addWidget(self.button_tumunu_sil)
        self.layout_mid.addWidget(self.frame_ders_ekle)
        self.frame_scrollArea = QtWidgets.QFrame(self.frame_middle)
        self.frame_scrollArea.setStyleSheet("")
        self.frame_scrollArea.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_scrollArea.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_scrollArea.setObjectName("frame_scrollArea")
        self.layout_scrollArea_awkward = QtWidgets.QHBoxLayout(self.frame_scrollArea)
        self.layout_scrollArea_awkward.setObjectName("layout_scrollArea_awkward")
        self.scrollArea = QtWidgets.QScrollArea(self.frame_scrollArea)
        self.scrollArea.setStyleSheet("QLineEdit, QComboBox, QSpinBox {\n"
"border: 1px solid rgb(200,200,200);\n"
"background-color: rgb(244,244,244);\n"
"border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton {\n"
"border: 1px solid rgb(211,111,111);\n"
"background-color: rgb(244,244,244);\n"
"color: rgb(211,111,111);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"background-color: rgb(211,111,111);\n"
"color:white;\n"
"}\n"
"\n"
"\n"
"")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 913, 260))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.layout_scrollAreaWidgets = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.layout_scrollAreaWidgets.setObjectName("layout_scrollAreaWidgets")
        self.frame_scrollArea_content = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_scrollArea_content.setStyleSheet("font: 87 10pt \"Segoe UI Black\";\n"
"")
        self.frame_scrollArea_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_scrollArea_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_scrollArea_content.setObjectName("frame_scrollArea_content")
        self.layout_scrollArea_content = QtWidgets.QVBoxLayout(self.frame_scrollArea_content)
        self.layout_scrollArea_content.setContentsMargins(-1, -1, -1, 10)
        self.layout_scrollArea_content.setSpacing(5)
        self.layout_scrollArea_content.setObjectName("layout_scrollArea_content")
        self.lesson_header_frame = QtWidgets.QFrame(self.frame_scrollArea_content)
        self.lesson_header_frame.setMinimumSize(QtCore.QSize(0, 40))
        self.lesson_header_frame.setMaximumSize(QtCore.QSize(16777215, 41))
        self.lesson_header_frame.setStyleSheet("background-color: rgb(222,222,222);\n"
"border-radius: 8px;")
        self.lesson_header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lesson_header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lesson_header_frame.setObjectName("lesson_header_frame")
        self.layout_ders_adi = QtWidgets.QHBoxLayout(self.lesson_header_frame)
        self.layout_ders_adi.setObjectName("layout_ders_adi")
        self.text_dersin_adi = QtWidgets.QLabel(self.lesson_header_frame)
        self.text_dersin_adi.setMaximumSize(QtCore.QSize(9999, 23))
        self.text_dersin_adi.setObjectName("text_dersin_adi")
        self.layout_ders_adi.addWidget(self.text_dersin_adi)
        self.text_harf_notu = QtWidgets.QLabel(self.lesson_header_frame)
        self.text_harf_notu.setMinimumSize(QtCore.QSize(100, 0))
        self.text_harf_notu.setMaximumSize(QtCore.QSize(113, 16777215))
        self.text_harf_notu.setObjectName("text_harf_notu")
        self.layout_ders_adi.addWidget(self.text_harf_notu)
        self.text_kredisi = QtWidgets.QLabel(self.lesson_header_frame)
        self.text_kredisi.setMinimumSize(QtCore.QSize(100, 0))
        self.text_kredisi.setMaximumSize(QtCore.QSize(80, 16777215))
        self.text_kredisi.setObjectName("text_kredisi")
        self.layout_ders_adi.addWidget(self.text_kredisi)
        self.empty_label = QtWidgets.QLabel(self.lesson_header_frame)
        self.empty_label.setMinimumSize(QtCore.QSize(35, 0))
        self.empty_label.setMaximumSize(QtCore.QSize(35, 35))
        self.empty_label.setText("")
        self.empty_label.setObjectName("empty_label")
        self.layout_ders_adi.addWidget(self.empty_label)
        self.layout_ders_adi.setStretch(0, 7)
        self.layout_ders_adi.setStretch(1, 1)
        self.layout_ders_adi.setStretch(2, 1)
        self.layout_ders_adi.setStretch(3, 1)
        self.layout_scrollArea_content.addWidget(self.lesson_header_frame)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.layout_scrollArea_content.addItem(spacerItem2)
        self.layout_scrollAreaWidgets.addWidget(self.frame_scrollArea_content)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.layout_scrollArea_awkward.addWidget(self.scrollArea)
        self.layout_mid.addWidget(self.frame_scrollArea)
        self.layout_mid.setStretch(0, 12)
        self.layout_mid.setStretch(1, 88)
        self.layout_central.addWidget(self.frame_middle)
        self.frame_bottom = QtWidgets.QFrame(self.centralwidget)
        self.frame_bottom.setStyleSheet("#frame_bottom{\n"
"background-color: rgb(232,229,233);\n"
"font: 87 10pt \"Segoe UI Black\";\n"
"border-radius: 10px;\n"
"border: 1px solid rgb(222,222,222)}\n"
"\n"
"QFrame > * {\n"
"background-color: rgb(232,229,233);\n"
"font: 87 10pt \"Segoe UI Black\";\n"
"}\n"
"")
        self.frame_bottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_bottom.setObjectName("frame_bottom")
        self.layout_bottom = QtWidgets.QHBoxLayout(self.frame_bottom)
        self.layout_bottom.setObjectName("layout_bottom")
        self.button_hesapla = QtWidgets.QPushButton(self.frame_bottom)
        self.button_hesapla.setMinimumSize(QtCore.QSize(100, 35))
        self.button_hesapla.setMaximumSize(QtCore.QSize(100, 35))
        self.button_hesapla.setStyleSheet("QPushButton{\n"
"border: 1px solid rgb(111,211,111);\n"
"border-radius: 10px;\n"
"background-color: white;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"background-color: rgb(111,211,111);\n"
"color: white;\n"
"}")
        self.button_hesapla.setObjectName("button_hesapla")
        self.layout_bottom.addWidget(self.button_hesapla)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_bottom.addItem(spacerItem3)
        self.text_by_anil_ergan = QtWidgets.QLabel(self.frame_bottom)
        self.text_by_anil_ergan.setMinimumSize(QtCore.QSize(200, 0))
        self.text_by_anil_ergan.setMaximumSize(QtCore.QSize(300, 16777215))
        self.text_by_anil_ergan.setStyleSheet("color: rgb(200,200,210);\n"
"")
        self.text_by_anil_ergan.setAlignment(QtCore.Qt.AlignCenter)
        self.text_by_anil_ergan.setObjectName("text_by_anil_ergan")
        self.layout_bottom.addWidget(self.text_by_anil_ergan)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_bottom.addItem(spacerItem4)
        self.text_agno = QtWidgets.QLabel(self.frame_bottom)
        self.text_agno.setMinimumSize(QtCore.QSize(80, 0))
        self.text_agno.setMaximumSize(QtCore.QSize(80, 16777215))
        self.text_agno.setStyleSheet("color: rgb(111,111,211);\n"
"font: 87 10pt \"Segoe UI Black\";\n"
"")
        self.text_agno.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.text_agno.setObjectName("text_agno")
        self.layout_bottom.addWidget(self.text_agno)
        self.text_agno_ekran = QtWidgets.QLabel(self.frame_bottom)
        self.text_agno_ekran.setMinimumSize(QtCore.QSize(50, 35))
        self.text_agno_ekran.setMaximumSize(QtCore.QSize(50, 35))
        self.text_agno_ekran.setSizeIncrement(QtCore.QSize(100, 0))
        self.text_agno_ekran.setBaseSize(QtCore.QSize(100, 0))
        self.text_agno_ekran.setStyleSheet("border: 2px solid rgb(111,111,211);\n"
"color: white;\n"
"border-radius: 8px;\n"
"background-color: rgb(111,111,211);")
        self.text_agno_ekran.setText("")
        self.text_agno_ekran.setAlignment(QtCore.Qt.AlignCenter)
        self.text_agno_ekran.setObjectName("text_agno_ekran")
        self.layout_bottom.addWidget(self.text_agno_ekran)
        self.layout_central.addWidget(self.frame_bottom)
        self.layout_central.setStretch(0, 2)
        self.layout_central.setStretch(1, 7)
        self.layout_central.setStretch(2, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GPA Calculator"))
        self.text_tamamlanmis_kredi.setText(_translate("MainWindow", "Tamamlanmış Kredi"))
        self.gpa_input_text.setText(_translate("MainWindow", "Güncel Agno"))
        self.button_kaydet.setText(_translate("MainWindow", "Kaydet"))
        self.button_ders_ekle.setText(_translate("MainWindow", "Ders Ekle"))
        self.button_tumunu_sil.setText(_translate("MainWindow", "Tümünü Sil"))
        self.text_dersin_adi.setText(_translate("MainWindow", "Dersin Adı"))
        self.text_harf_notu.setText(_translate("MainWindow", "Harf Notu"))
        self.text_kredisi.setText(_translate("MainWindow", "Kredisi"))
        self.button_hesapla.setText(_translate("MainWindow", "Hesapla"))
        self.text_by_anil_ergan.setText(_translate("MainWindow", "by Anıl Ergan"))
        self.text_agno.setText(_translate("MainWindow", "AGNO:"))
import icons_rc
